# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Nuestros Quesos
#email: your-email@example.com
#twitter_username: jekyllrb
#github_username:  jekyll
locale: es-ES
description: >- # this means to ignore newlines until "baseurl:"
  Un Comunidad de Queseros Artesanales
domain: www.nuestrosquesos.com 
baseurl: # the subpath of your site, e.g. /blog
url: https://www.nuestrosquesos.com # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:year/:month/:day/:title/ 
date_format: "%B %-d, %Y"
# Theme settings
logo: /assets/img/logo.jpg

# Build settings
theme: jekyll-theme-so-simple
# theme: minima
# remote_theme: "mmistakes/so-simple-theme@3.2.0"
search_full_content: true

category_archive_path: "/categorias/#"
tag_archive_path: "/etiquetas/#"

sass:
  style: compressed

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

collections:
- directory

# Pagination Settings
paginate: 20
paginate_path: /page:num/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-compose
  - jekyll-redirect-from
  - jekyll-leaflet

exclude:
  - LICENSE
  - README.md
  - Rakefile
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

  
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
